version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.angular
    ports:
      - "4200:4200"
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
